branch-defaults:
  default:
    environment: Application-main
  main:
    environment: Application-main
environment-defaults:
  Application-main:
    branch: null
    repository: null
global:
  application_name: Application
  default_ec2_keyname: php
  default_platform: PHP 8.4 running on 64bit Amazon Linux 2023
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
